version: "3.5"
services:

  config-file-server:
    image: config-file-server
    restart: always
    build:
      context: ./config-file-server
      dockerfile: Dockerfile
    expose:
      - 9101
    ports:
      - 9101:9101
    
  eureka-server:
    image: eureka-server
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose:
      - 9102
    ports:
      - 9102:9102
    depends_on:
      - config-file-server
    environment:
      spring.cloud.config.uri: http://config-file-server:9101
      EUREKA_HOST: eureka-server

  pgdb:
    image: postgres:16
    container_name: db-tp-e-commerce
    hostname: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tp-e-commerce
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5435:5432/tcp
    volumes:
      - "./pg_db:/var/lib/postgresql/data"

  microservice-produits:
    image: microservice-produits
    restart: always
    build:
      context: ./microservice-produits
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - config-file-server
      - eureka-server
      - pgdb
    environment:
      spring.cloud.config.uri: http://config-file-server:9101
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      EUREKA_HOST: eureka-server

  microservice-commandes:
    image: microservice-commandes
    restart: always
    build:
      context: ./microservice-commandes
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - config-file-server
      - eureka-server
      - pgdb
    environment:
      spring.cloud.config.uri: http://config-file-server:9101
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      EUREKA_HOST: eureka-server

  microservice-paiements:
    image: microservice-paiements
    restart: always
    build:
      context: ./microservice-paiements
      dockerfile: Dockerfile
    expose: 
      - 8082
    ports:
      - 8082:8082
    depends_on:
      - config-file-server
      - eureka-server
      - pgdb
    environment:
      spring.cloud.config.uri: http://config-file-server:9101
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      EUREKA_HOST: eureka-server

  zuul-server:
    image: zuul-server
    restart: always
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    expose: 
      - 9004
    ports:
      - 9004:9004
    depends_on:
      - microservice-produits
      - microservice-commandes
      - microservice-paiements
    environment:
      spring.cloud.config.uri: http://config-file-server:9101
      EUREKA_HOST: eureka-server

  microservice-clients-ui:
    image: microservice-clients-ui
    restart: always
    volumes:
      - './microservice-clients-ui:/usr/src/app'
      - '/usr/src/app/node_modules'
    build:
      context: ./microservice-clients-ui
      dockerfile: Dockerfile
    expose: 
      - 4200
    ports:
      - 4200:4200
    depends_on:
      - microservice-produits
      - microservice-commandes
      - microservice-paiements
